services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '6431:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: transactionsdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
